### ISSUE TITLE
connect-ftp  Unable to find type [FluentFTP.FtpProfile]. error version 0.0.10

### ISSUE THREAD

**Issue by nevek2** [EvotecIT/Transferetto#11]
Hi,

When I try to connect to a FTP I get this error
`Unable to find type [FluentFTP.FtpProfile].
At C:\Program Files\WindowsPowerShell\Modules\Transferetto\0.0.10\Transferetto.psm1:183 char:9
+         [FluentFTP.FtpProfile] $FtpProfile,`

**Comment by nevek2** [comment]
Hi,

When i try your commands I get this:
***@***.***

Met vriendelijke groeten,
Kevin De Wulf
***@***.******@***.***>
Suikerkaai 81 - 9060 Zelzate
tel.: +32 (0)9 342 28 28
fax: +32 (0)9 342 28 18
ICT Medewerker
[http://www.pcsintjanbaptist.be/logopcsjb/Handtekening-versie-20201201.jpg]<http://www.pcsintjanbaptist.be/>

Van: Przemysław Kłys ***@***.***>
Verzonden: dinsdag 1 maart 2022 21:09
Aan: EvotecIT/Transferetto ***@***.***>
CC: De Wulf, Kevin ***@***.***>; Author ***@***.***>
Onderwerp: Re: [EvotecIT/Transferetto] connect-ftp Unable to find type [FluentFTP.FtpProfile]. error version 0.0.10 (Issue #11)


When you do Import-Module Transferetto does it work the way I show it?

[image]<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15063294%2F156241109-55a0bb78-4d19-4e8b-8f9c-4ac4893ab723.png&data=04%7C01%7C%7Cf62222ea8a46450b0ca208d9fbbf5d69%7C018bc399052646e68c6d3c80dcc2b861%7C0%7C0%7C637817622201707795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ymxHzpoye%2Fctuf34xoUWTOkfDjuEhZxN%2FFRAQqeMAeU%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEvotecIT%2FTransferetto%2Fissues%2F11%23issuecomment-1055814950&data=04%7C01%7C%7Cf62222ea8a46450b0ca208d9fbbf5d69%7C018bc399052646e68c6d3c80dcc2b861%7C0%7C0%7C637817622201707795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bYhlktCP6u28VfOcJZsrEY0WFJEwhse04Yc6xm16WO4%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF4SVS5MCEXKIEYE5TT364DU5Z2OZANCNFSM5PUJX2FA&data=04%7C01%7C%7Cf62222ea8a46450b0ca208d9fbbf5d69%7C018bc399052646e68c6d3c80dcc2b861%7C0%7C0%7C637817622201707795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6Nq1WoKD4Kmli3b8Ir5S%2FvLRZaFCuh5FLv6U6%2BV29%2Fw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf62222ea8a46450b0ca208d9fbbf5d69%7C018bc399052646e68c6d3c80dcc2b861%7C0%7C0%7C637817622201707795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fgJOw%2Fz63o2cg8MyjPP%2B9bwDNp4n%2BJIhM%2FbyHOvGyXw%3D&reserved=0> or Android<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf62222ea8a46450b0ca208d9fbbf5d69%7C018bc399052646e68c6d3c80dcc2b861%7C0%7C0%7C637817622201707795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YO%2FG36bULxEBwOZXYbFEzGUe4Q5JYTpLG8E58AL4jMc%3D&reserved=0>.

**Comment by PrzemyslawKlys** [comment]
```powershell
Get-Module -List Transferetto
$PSVersionTable
```

DO you have Net Framework 4.7.2+?

**Comment by PrzemyslawKlys** [comment]
Great. I need to somehow detect that in my modules and give people warnings.
