### ISSUE TITLE
Error: Exception calling "UploadFile" with "3" argument(s): "No such file"

### ISSUE THREAD

**Issue by g4rry420** [EvotecIT/Transferetto#12]
Hi, I am trying to run to put send files to remote server using sftp but I am facing this error. Can you please help me regarding this ? Thank you.

```
# Login via credentials
$SftpClient = Connect-SFTP -Server 'host address' -Username 'userName' -Password 'password'

Send-SFTPFile -SftpClient $SftpClient -LocalPath "C:\Users\gurki\Documents\Personal_Projects\Algorithms.txt" -RemotePath "C:\inetpub" -AllowOverride
Disconnect-SFTP -SftpClient $SftpClient

```

This error is howing up after running the command:
```

WARNING: Send-SFTPFile - Error: Exception calling "UploadFile" with "3" argument(s): "No such file"


Action     : UploadFile
Status     : False
LocalPath  : C:\Users\gurki\Documents\Personal_Projects\Algorithms.txt
RemotePath : C:\inetpub
Message    : Error: Exception calling "UploadFile" with "3" argument(s): "No such file"
```

**Comment by PrzemyslawKlys** [comment]
Does that file `"C:\Users\gurki\Documents\Personal_Projects\Algorithms.txt" exists? 
I believe RemotePath can't be "C:\Inetpub". THere's no "C:\" for remote. do a Get-SFTPList and see how it returns data and use it 

```powershell
Send-SFTPFile -SftpClient $SftpClient -LocalPath $File.FullName -RemotePath "/Temporary/$($File.Name)" -AllowOverride
```

**Comment by g4rry420** [comment]
Thank you for suggesting that. It worked for files but if there is folder and and inside it there are some files, it doesn't send that. Do have any suggestions regarding that ?

I have faced this error when I tried to send the `assets` folder

![Screenshot 2022-03-10 140111](https://user-images.githubusercontent.com/61521805/157735885-a0f55a5f-6902-4736-b9e3-70d0eea5a78e.png)

**Comment by PrzemyslawKlys** [comment]
Send-SftpDirectory?

**Comment by g4rry420** [comment]
This gives me error
![Screenshot 2022-03-10 152225](https://user-images.githubusercontent.com/61521805/157748203-d3b909ce-b659-47a0-8978-e29f5c9a058f.png)
It seems like https://github.com/EvotecIT/Transferetto/blob/c2e9e0623b0aa36e5ceeac4d0d4a8b361d21c9ad/Transferetto.psd1#L9, there is not Send-SFTPDirectory command ?

**Comment by PrzemyslawKlys** [comment]
Right, then you probably need to do your own logic - for example:

```powershell
Import-Module .\Transferetto.psd1 -Force

$SftpClient = Connect-SFTP -Server '192.168.241.187' -Verbose -Username 'test' -Password 'BiPassword90A'
Get-SFTPList -SftpClient $SftpClient | Format-Table
Get-SFTPList -SftpClient $SftpClient -Path "/Temporary" | Format-Table *

$ListFiles = Get-ChildItem -LiteralPath $PSScriptRoot\Upload -Recurse -File
foreach ($File in $ListFiles) {
    $Directory = [io.path]::GetDirectoryName($File.FullName)
    if ($Directory -eq "$PSScriptRoot\Upload") {
        Send-SFTPFile -SftpClient $SftpClient -LocalPath $File.FullName -RemotePath "/Temporary/$($File.Name)" -AllowOverride
    } else {
        Send-SFTPFile -SftpClient $SftpClient -LocalPath $File.FullName -RemotePath "/Temporary/$($Directory.Split('\')[-1])/$($File.Name)" -AllowOverride
    }
}

Disconnect-SFTP -SftpClient $SftpClient
```

**Comment by g4rry420** [comment]
I am getting error because the `assets` folder doesn't exist on the remote. Do you command to check if the folder exist on the remote and if not, then create that folder ?

**Comment by PrzemyslawKlys** [comment]
```powershell

$SftpClient = Connect-SFTP -Server '192.168.241.187' -Verbose -Username 'test' -Password 'BiPassword90A'
Get-SFTPList -SftpClient $SftpClient | Format-Table
Get-SFTPList -SftpClient $SftpClient -Path "/Temporary" | Format-Table *

$ListFiles = Get-ChildItem -LiteralPath $PSScriptRoot\Upload -Recurse -File
foreach ($File in $ListFiles) {
    $Directory = [io.path]::GetDirectoryName($File.FullName)
    if ($Directory -eq "$PSScriptRoot\Upload") {
        Send-SFTPFile -SftpClient $SftpClient -LocalPath $File.FullName -RemotePath "/Temporary/$($File.Name)" -AllowOverride
    } else {
        #$RemotePath = "/Temporary/$($Directory.Split('\')[-1])/$($File.Name)"
        $RemoteFolder = "/Temporary/$($Directory.Split('\')[-1])"
        $List = Get-SFTPList -SftpClient $SftpClient -Path $RemoteFolder -WarningAction SilentlyContinue
        if (-not $List) {
            $SftpClient.CreateDirectory($RemoteFolder)
        }
        Send-SFTPFile -SftpClient $SftpClient -LocalPath $File.FullName -RemotePath "$RemoteFolder/$($File.Name)" -AllowOverride
    }
}

Disconnect-SFTP -SftpClient $SftpClient
```

**Comment by g4rry420** [comment]
Thank you for this solution. 
My apologies, I know I keep on asking you questions.
But the above solution doesn't consider for the nested folder paths
For eg:-
```
folder1
    nestedFolder1
        file1.txt
    nestedFolder2
        file2.txt
    nestedFolder3
        file3.txt
file1.txt
file2.txt
```
The above solution do copy all the files but it only considers the folder, in which there are files. So, from above example:

```
nestedFolder1
     file1.txt
nestedFolder2
     file2.txt
nestedFolder3
     file3.txt
file1.txt
file2.txt
```
Only, these folder and files exist in the remote. the `folder1` doesn't exist on the remote. The reason why it is important for `folder1` on exist on remote is beacuse I am pushing the build of site generated onto the remote server.

I am not an expert on powershell. Can you please suggest me solution for this ?
