### ISSUE TITLE
Fero

### ISSUE THREAD

**Issue by FeroKli** [EvotecIT/Transferetto#15]
Dear all, 
I am trying to send more files to FTP server using Transferetto module and next part of script:

foreach ($RemoteFile in $ListFiles) {
Send-FTPFile -Client $Client -LocalPath $ListFiles.FullName -RemotePath "/TEMP/$($RemoteFile.Name)" -RemoteExists OverWrite
}

But I am getting an error: "Remove-EmptyValue : The term 'Remove-EmptyValue' is not recognized as the name of a cmdlet, function, script file, or operable program." 

I could not find "Remove-EmptyValue" in the PowerShell commands.
Have you please any idea, how to solve it?
Thanks
Fero

**Comment by FeroKli** [comment]
Whole script to send file is:

$Client = Connect-FTP -Server 'FTPServerName' -Verbose -Username 'login' -Password 'password' -EncryptionMode Explicit -ValidateAnyCertificate
# List files
$List = Get-FTPList -Client $Client
$ListFiles = Get-ChildItem -LiteralPath $PSScriptRoot\Upload
foreach ($RemoteFile in $ListFiles) {
Send-FTPFile -Client $Client -LocalPath $ListFiles.FullName -RemotePath "/TEMP/$($RemoteFile.Name)" -RemoteExists OverWrite
}
Disconnect-FTP -Client $Client    

I get the error only when I am trying to send more then one file.
Thanks.
Fero

**Comment by PrzemyslawKlys** [comment]
I've republished new version which fixes this issue. Sorry.
