### ISSUE TITLE
Connect-FTP -EncryptionMode

### ISSUE THREAD

**Issue by bastienperez** [EvotecIT/Transferetto#20]
Hello,
First, thanks for your awesome work! (again)

I have a little issue with Connect FTPS ``Connect-FTP -EncryptionMode xxx``
The property ``EncryptionMode`` can't be found in the _FluentFTP.FtpClient_ ``$Client``:
```
C:\Program Files\WindowsPowerShell\Modules\Transferetto\0.0.15\Transferetto.psm1:233 : 28
+     if ($EncryptionMode) { $Client.EncryptionMode = $EncryptionMode }
```
``Connect-FTP -Autoconnect`` works.

``EncryptionMode``  must be part of config I suppose?

```powershell
$ftpSession = Connect-FTP -Server 'xxx' -Username 'yyyyy' -Password 'zzz' -AutoConnect

$ftpSession.Config.EncryptionMode
Implicit
```

**Comment by PrzemyslawKlys** [comment]
You are right.  Since I didn't have tests for this I didn't notice when updating library to newest version. It must have changed at some point. Someone should write ore tests :p

**Comment by bastienperez** [comment]
Thanks! I will try this fix and let you know 💪.
