### ISSUE TITLE
Any way to connect to SFTP using key pairs?

### ISSUE THREAD

**Issue by harleykin** [EvotecIT/Transferetto#21]
I'm working on a project that needs an FTP solution and I'm eyeing this module as a possible viable solution.  :)   I've been playing with downloading files from Box FTP and so far that's gone very well.  I also will need to upload to an SFTP site that uses SSH keys for authentication rather than username/password.  Is this something you are considering to add in a future release of Transferetto?

Thanks!

**Comment by PrzemyslawKlys** [comment]
https://github.com/EvotecIT/Transferetto/blob/master/Public/Connect-SFTP.ps1 has PrivateKey option - is that not enough?

**Comment by harleykin** [comment]
Hrm, I will play around with this today to see if I can get it to work.  I didn't see it on the blog post and hadn't yet made it through all of your examples on here.  Apologies!

**Comment by harleykin** [comment]
OK I'm doing something wrong with its usage.  I am trying one of the examples from the blog post using...

```
$SftpClient = Connect-SFTP -Server 'sftp.server.com' -PrivateKey "C:\Path\to\My\Keys\Folder" -Verbose
Get-SFTPList -SftpClient $SftpClient | Format-Table
Get-SFTPList -SftpClient $SftpClient -Path "/Temporary" | Format-Table *
```

... and I'm still getting a prompt for username.  What am I missing?

**Comment by PrzemyslawKlys** [comment]
The way i understand is - you still need to have username in the system you are trying to connect right, how else the system is supposed to know which user uses this private key? So username is required and then private key is required (not a folderpath, but a file path). 

![image](https://user-images.githubusercontent.com/15063294/202538100-4ea2a604-7e87-4f52-8fac-77cc2832e72b.png)

**Comment by harleykin** [comment]
Hrm, ok I see what you are saying, my apologies.  I'm getting a step closer.  I copied my keys to my testing folder because I kept getting access denied, but even there it can't access my PrivateKey.  Is it looking for any particular format?

`$SftpClient = Connect-SFTP -Server 'sftp.server.com' -Username "test.user" -PrivateKey "C:\BoxTesting" -Verbose`

This was the result:

```
WARNING: Connect-SFTP - Error: Cannot convert value "C:\BoxTesting" to type "Renci.SshNet.PrivateKeyFile". Error: "Access to the path 'C:\
BoxTesting' is denied."
Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Transferetto\0.0.16\Transferetto.psm1:357 char:23
+ ... ftpClient | Add-Member -Name 'Error' -Value $($_.Exception.Message) - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
 
WARNING: Connect-SFTP - Error: You cannot call a method on a null-valued expression.
```

**Comment by PrzemyslawKlys** [comment]
It's a FILE not a folder. That means C:\BoxTesting\YourPrivateKey.key file

**Comment by harleykin** [comment]
I see.  I'm spoiled by other apps merely being pointed to the folder and keyfiles being auto-detected.  Thank you, again, for pointing me in the right direction.
