### ISSUE TITLE
How to download all child items?

### ISSUE THREAD

**Issue by harleykin** [EvotecIT/Transferetto#22]
I have an FTP site with a folder that has many sub folders, and some of those have sub folders and files.  Is there an easy to way download all items and its child items, regardless if they're files or folders or both?

**Comment by PrzemyslawKlys** [comment]
```powershell
$Client = Connect-FTP -Server 'test.rebex.net' -Verbose -Username 'demo' -Password 'password' -EncryptionMode Auto
$List = Get-FTPList -Client $Client
$List | Format-Table
Get-FTPDirectory -Client $Client -LocalPath 'C:\Temp\FTP' -RemotePath "/" -Verbose
Disconnect-FTP -Client $Client
```

This works just fine.

**Comment by harleykin** [comment]
I see, I was thinking too granular.  Thank you, I shall play with that command instead!

Love your works, thank you so much for your time and efforts!

**Comment by harleykin** [comment]
Hrm, I see how to find files to download, how do you specify folders to grab?
