### ISSUE TITLE
why I got this error :(  

### ISSUE THREAD

**Issue by NSH531** [EvotecIT/Transferetto#25]
error:
```

Action     : UploadFile
LocalPath  : u:\
RemotePath : /SFTP - Sandbox Integration/2
Status     : False
Message    : Failed


```

tnx
nate

**Comment by PrzemyslawKlys** [comment]
Could you put even less effort to actually provide some information? How am I supposed to know what you are doing based on an output on a single file. I don't even know what you are using.
