### ISSUE TITLE
is it possible to preserve file/folder properties ?

### ISSUE THREAD

**Issue by RajasekharKomirshetty** [EvotecIT/Transferetto#28]
Hello,

I'm using Receive-FTPDirectory ( and Receive-FTPfile) to download files/folders from FTP server. However I noticed that the file properties like created, modified, owner are getting updated. Is there a way we can preserve these properties like they are before downloading?

Thank you

**Comment by PrzemyslawKlys** [comment]
You can read them before you download them, download the file and then use

```powershell
$file = Get-Item C:\Path\TO\File.txt
$file.LastWriteTime = xxx
$file..... = dsdsd
```
