### ISSUE TITLE
Download only specific files with prefix or suffix and if not already downloaded in localfodler

### ISSUE THREAD

**Issue by stefancvetkovic** [EvotecIT/Transferetto#31]
So I have a list of files from your example, but I want just to filter it with some names and then to check if these names alredy exists in folder, and if not, then download it.

**Comment by PrzemyslawKlys** [comment]
Use Get-FtpList to find what's on FTP, use Get-ChildItem to find whats' local, loop thru get-ftplist output and see if it already exists locally. It's a simple loop with verification of existance. You can also do this in the same loop to check for prefix or suffix.
