### ISSUE TITLE
(v0.0.18) Connect-SFTP with PrivateKey fails 

### ISSUE THREAD

**Issue by DeeTigIT** [EvotecIT/Transferetto#32]
I'm trying to connect to our business SFTP server using key authentication:

Connect-SFTP -Server $Server -Port $Port -Username $User -PrivateKey $KeyFilePath

With v0.0.17 and earlier this poses no problem.
But with v0.0.18 an algoritme error occurs at the server side and connection is refused:

**WARNING: Connect-SFTP - Error: Exception calling "Connect" with "0" argument(s): "The connection was closed by the server: ssh disconnect host not allowed to connect (HostNotAllowedToConnect)."**

**Could it be that a change a needed regarding [Renci.SshNet.PrivateKeyFile]$PrivateKey in Connect-SFTP?**

Because I noticed a difference in [Renci.SshNet.PrivateKeyFile]$PrivateKey:

**- v0.0.18**

HostKeyAlgorithms                     Key
-----------------                     ---
{rsa-sha2-512, rsa-sha2-256, ssh-rsa} ssh-rsa

**- v0.0.17**

HostKey
------
Renci.SshNet.Security.KeyHostAlgorithm

**Comment by PrzemyslawKlys** [comment]
The library was updated: 
- https://github.com/sshnet/SSH.NET/releases/tag/2023.0.0

So something must have changed

```ps
PS C:\Support\GitHub\Transferetto> [Renci.SshNet.PrivateKeyFile]::new    

OverloadDefinitions
-------------------
Renci.SshNet.PrivateKeyFile new(Renci.SshNet.Security.Key key)
Renci.SshNet.PrivateKeyFile new(System.IO.Stream privateKey)
Renci.SshNet.PrivateKeyFile new(string fileName)
Renci.SshNet.PrivateKeyFile new(string fileName, string passPhrase)
Renci.SshNet.PrivateKeyFile new(System.IO.Stream privateKey, string passPhrase)
```

```ps
PS C:\Support\GitHub\Transferetto> [Renci.SshNet.SftpClient]::new 

OverloadDefinitions
-------------------
Renci.SshNet.SftpClient new(Renci.SshNet.ConnectionInfo connectionInfo)
Renci.SshNet.SftpClient new(string host, int port, string username, string password)
Renci.SshNet.SftpClient new(string host, string username, string password)
Renci.SshNet.SftpClient new(string host, int port, string username, Params Renci.SshNet.IPrivateKeySource[] keyFiles)
Renci.SshNet.SftpClient new(string host, string username, Params Renci.SshNet.IPrivateKeySource[] keyFiles)
```

I don't see anhything that is wrong or different from earlier version. As I don't have way to test this, you would need to so some digging :/

**Comment by DeeTigIT** [comment]
Switching to another key type in the communication (EdDSA Ed25519 255bits) solved this issue. The public part of this new key I added to the server keystore. I will close the call.
