### ISSUE TITLE
Support for TLS 1.3

### ISSUE THREAD

**Issue by ndinev** [EvotecIT/Transferetto#33]
I installed latest version:
Install-Module -Name Transferetto

The I tried to connect to filezilla server with TLS 1.2 -> works fine
Tried same script while filezilla server is configured for TLS 1.3 only -> fails

Before providing more details I am wondering if TLS 1.3 is supported by Transferetto?

[FluentFtp ](https://github.com/robinrodricks/FluentFTP) claims support of 1.3 TLS

**Comment by PrzemyslawKlys** [comment]
If you click on the link it will bring you to:
- https://github.com/robinrodricks/FluentFTP/wiki/FTPS-Connection-using-GnuTLS
 
They basically say to include FluentFTP GnuTLS library, which I guess needs GnuTLS installed on machine. Maybe it would be possible to include a portable version of it. Not super straightforward atm.

**Comment by PrzemyslawKlys** [comment]
Hrmms,

>For Windows, we package the GnuTLS C library as pre-compiled DLLs within our Nuget package.
It is automatically copied into your project and linked for usage by your build process. 

I would need to figure out the loading of libraries.

**Comment by ndinev** [comment]
I will be happy to be able to use Transferetto with TLS 1.3 even if I need manually to configure something. Some instruction will be helpful

**Comment by PrzemyslawKlys** [comment]
Can you try `Install-Module Transferetto -AllowPrerelease` and see if TLS 1.3 works? I don't really have anything to test on.

**Comment by ndinev** [comment]
@PrzemyslawKlys You can test with free version of filezilla server - https://filezilla-project.org/download.php?platform=win64&type=server
In Server config select TLS1.3 only and then try  Transferetto with FTPS connection
