### ISSUE TITLE
v0.0.19-Alpha1 : untrusted publisher

### ISSUE THREAD

**Issue by DeeTigIT** [EvotecIT/Transferetto#35]
Running a script using the v0.0.19-Alpha1:

Do you want to run software from this **untrusted publisher**?
File <mypath>\modules\Transferetto\Transferetto.psm1 is published by CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys EVOTEC, L=Mikołów, C=PL and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):

**Comment by PrzemyslawKlys** [comment]
`Install-Module Transferetto -Force -AllowPrerelease -Force -SkipPublisherCheck`

The certificate is ok. If you have older version of Transferetto installed about 6 months ago I've changed certificate so new updates with this new certificate will trigger this warning.
