### ISSUE TITLE
Different port number

### ISSUE THREAD

**Issue by bbbkada** [EvotecIT/Transferetto#36]
Trying to connect to a server that I can connect to with filezilla. It runs on a custom portnumber, and I haven't seen any examples that uses other than default portnumbers ?  I'm running Request-FTPConfiguration -Server 'sitename.com:2121' and get no results.
Is it a sign that i'm using the portnumber wrong or does transferetto fail to find a way to connect ?
The server is a SFTPGo docker with very few settings, but Filezilla accepts it.

**Comment by PrzemyslawKlys** [comment]
Connect-FTP -Port xxx -XXX 

For Request configuration I actually didn't added it. But Request-FTPConfiguration isn't really needed.
