### ISSUE TITLE
Transferetto 0.0.19 : Could not load file or assembly Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by DeeTigIT** [EvotecIT/Transferetto#37]
PS C:\Program Files\PowerShell\7> Install-Module Transferetto -Force -AllowPrerelease -SkipPublisherCheck
PS C:\Program Files\PowerShell\7> get-module -name transferetto -ListAvailable

    Directory: D:\Mijn gebruikers\ACCOUNT\Documenten\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     0.0.19                Transferetto                        Core,Desk {Compare-FTPFile, Connect-FTP, Connect-SFTP, Connect-SSH…}

**PS C:\Program Files\PowerShell\7> import-module -name transferetto -Force
Add-Type: D:\Mijn gebruikers\ACCOUNT\Documenten\PowerShell\Modules\transferetto\0.0.19\Transferetto.Libraries.ps1:4
Line |
   4 |  Add-Type -Path $PSScriptRoot\Lib\Standard\Microsoft.Bcl.AsyncInterfac …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.**
PS C:\Program Files\PowerShell\7> GET-PACKageProvider nuget

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate

PS C:\Program Files\PowerShell\7> $PSVERsionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by PrzemyslawKlys** [comment]
I can replicate this on PS 7. Thank you.

**Comment by PrzemyslawKlys** [comment]
I've removed new SSH.NET and downgraded to old version. There seems to be an issue with this library in PS 7 now. Lets hope next version will be better
