### ISSUE TITLE
Can't Download FTP File

### ISSUE THREAD

**Issue by paynent** [EvotecIT/Transferetto#9]
Sorry I'm not sure if I'm doing something wrong but I'm getting this error when I try to download a file

Receive-FTPFile : Cannot process argument transformation on parameter 'RemoteFile'. Cannot convert the "/scdeploy/cnr.msi" value of type "System.String" to type 
"FluentFTP.FtpListItem[]"

**Comment by PrzemyslawKlys** [comment]
how are you using it?

**Comment by paynent** [comment]
I was putting /scdeploy/cnr.msi directly into the -remotefile flag. Apparently that doesn't work?

Using the examples on that website I was able to use the variable to search the directory for the filename cnr.msi and the plug that into the -remotefile instead which worked. So I have what I need. not sure why the direct ftp filepath doesn't work though.

**Comment by PrzemyslawKlys** [comment]
There are two parameter sets. One for native object type is `[FluentFTP.FtpListItem]` which allows you to download files using the way you just did. 

Alternatively, you can use RemotePath which downloads the file based on a string.
